-- Funciones nuevas (Tanda 2). Ejecuta en Supabase → SQL Editor.

-- "¿Quién ha visto tu perfil?"
create table if not exists profile_views (
  id bigint generated by default as identity primary key,
  viewer_id uuid references profiles(id) on delete cascade,
  profile_id uuid references profiles(id) on delete cascade,
  created_at timestamptz default now()
);
create index if not exists idx_profile_views_profile on profile_views(profile_id);

alter table profile_views enable row level security;

-- El dueño del perfil ve quién le ha visto
drop policy if exists "see my viewers" on profile_views;
create policy "see my viewers" on profile_views
  for select using (auth.uid() = profile_id);

-- Cualquiera autenticado puede registrar SU visita
drop policy if exists "log a view" on profile_views;
create policy "log a view" on profile_views
  for insert with check (auth.uid() = viewer_id);


-- Sesiones de estudio (Pomodoro) + ranking
create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  minutes int not null,
  created_at timestamptz default now()
);
create index if not exists idx_study_user on study_sessions(user_id, created_at);

alter table study_sessions enable row level security;

-- Cada uno inserta lo suyo
drop policy if exists "insert own study" on study_sessions;
create policy "insert own study" on study_sessions
  for insert with check (auth.uid() = user_id);

-- Todos pueden leer (para el ranking con amigos)
drop policy if exists "read study" on study_sessions;
create policy "read study" on study_sessions
  for select using (true);
